import { paths } from './paths'
import {
  IconCalendar,
  IconChart,
  IconClipboard,
  IconCreditCard,
  IconFileText,
  IconHome,
  IconMedical,
  IconServices,
  IconSpecialist,
  IconTooth,
  IconUser,
  IconUsers,
  IconMail,
} from '@/components/icons/icons'

export const publicNavItems = [
  { to: paths.home, label: 'Inicio', Icon: IconHome, end: true },
  { to: paths.services, label: 'Servicios', Icon: IconServices },
  { to: paths.specialists, label: 'Especialistas', Icon: IconSpecialist },
  { to: paths.bookAppointment, label: 'Agendar cita', Icon: IconCalendar },
]

export const patientMenuItems = [
  { to: paths.dashboard, label: 'Mi espacio', Icon: IconHome, end: true },
  { to: paths.myAppointments, label: 'Mis citas', Icon: IconCalendar },
  { to: paths.myTreatment, label: 'Mi tratamiento', Icon: IconTooth },
  { to: paths.myPayments, label: 'Mis pagos', Icon: IconCreditCard },
  { to: paths.messages, label: 'Mensajes', Icon: IconMail },
  { to: paths.myProfile, label: 'Mi perfil', Icon: IconUser },
]

export const privateMenuItems = [
  {
    to: paths.dashboard,
    label: 'Menu modulos',
    Icon: IconHome,
    end: true,
    activePaths: [paths.appointmentHistory, paths.summary],
  },
  { to: paths.patients, label: 'Paciente', Icon: IconUser },
  { to: paths.specialties, label: 'Especialidades', Icon: IconServices },
  { to: paths.doctors, label: 'Médico', Icon: IconSpecialist },
  { to: paths.appointments, label: 'Citas', Icon: IconCalendar },
  { to: paths.calendar, label: 'Calendario', Icon: IconCalendar },
  { to: paths.odontogram, label: 'Odontograma', Icon: IconTooth },
  { to: paths.treatments, label: 'Tratamiento', Icon: IconClipboard },
  { to: paths.payments, label: 'Pagos', Icon: IconCreditCard },
  { to: paths.users, label: 'Usuarios', Icon: IconUsers },
  { to: paths.reports, label: 'Reporte', Icon: IconFileText },
]

export const privateModules = [
  {
    id: 'usuarios',
    to: paths.users,
    title: 'Usuarios',
    tone: 'users',
    description: 'Control de permiso y accesos del personal',
    Icon: IconUsers,
    assetName: 'icousuario.png',
  },
  {
    id: 'pacientes',
    to: paths.patients,
    title: 'Paciente',
    description: 'Expediente clinico e historial medico',
    Icon: IconMedical,
    assetName: 'icopaciente.png',
  },
  {
    id: 'especialidades',
    to: paths.specialties,
    title: 'Especialidades',
    description: 'Areas odontologicas registradas',
    Icon: IconServices,
    assetName: 'iconoespecial.png',
  },
  {
    id: 'medicos',
    to: paths.doctors,
    title: 'Medico',
    description: 'Planilla de doctores y sus horarios',
    Icon: IconSpecialist,
    assetName: 'icomedico.png',
  },
  {
    id: 'tratamientos',
    to: paths.treatments,
    title: 'Tratamiento',
    description: 'Catalogo de procedimientos y precios',
    Icon: IconClipboard,
    assetName: 'icotratamiento.png',
  },
  {
    id: 'citas',
    to: paths.appointments,
    title: 'Citas',
    description: 'Agendamiento y control de turnos',
    Icon: IconCalendar,
    assetName: 'icocita.png',
  },
  {
    id: 'odontograma',
    to: paths.odontogram,
    title: 'Odontograma',
    description: 'Mapa interactivo por paciente',
    Icon: IconTooth,
    assetName: 'icoodontograma.png',
  },
  {
    id: 'historial-citas',
    to: paths.appointmentHistory,
    title: 'Historial Citas',
    description: 'Registro historico de atencion',
    Icon: IconCalendar,
    assetName: 'icohistorialcitas.png',
  },
  {
    id: 'calendario',
    to: paths.calendar,
    title: 'Calendario',
    description: 'Vista General mensual de la clinica',
    Icon: IconCalendar,
    assetName: 'icocalendario.png',
  },
  {
    id: 'pagos',
    to: paths.payments,
    title: 'Pagos',
    description: 'Ingreso, abono y presupuesto',
    Icon: IconCreditCard,
    assetName: 'icopagos.png',
  },
  {
    id: 'reportes',
    to: paths.reports,
    title: 'Reporte',
    description: 'Generacion de informe ejecutivo',
    Icon: IconFileText,
    assetName: 'icoreporte.png',
  },
  {
    id: 'resumen',
    to: paths.summary,
    title: 'Resumen',
    description: 'Estadistica y meta mensual',
    Icon: IconChart,
    assetName: 'icoresumen.png',
  },
]
