export const paths = {
  home: '/',
  services: '/servicios',
  specialists: '/especialistas',
  bookAppointment: '/agendar',
  dashboard: '/panel',
  users: '/panel/usuarios',
  patients: '/panel/pacientes',
  specialties: '/panel/especialidades',
  doctors: '/panel/medicos',
  treatments: '/panel/tratamientos',
  appointments: '/panel/citas',
  odontogram: '/panel/odontograma',
  appointmentHistory: '/panel/historial-citas',
  payments: '/panel/pagos',
  reports: '/panel/reportes',
  summary: '/panel/resumen',
  calendar: '/panel/calendario',
  notFound: '*',
}
