export const paths = {
  home: '/',
  services: '/servicios',
  specialists: '/especialistas',
  bookAppointment: '/agendar',
  dashboard: '/panel',
  users: '/panel/usuarios',
  patients: '/panel/pacientes',
  newPatient: '/panel/pacientes?nuevo=1',
  specialties: '/panel/especialidades',
  doctors: '/panel/medicos',
  treatments: '/panel/tratamientos',
  appointments: '/panel/citas',
  newAppointment: '/panel/citas?nuevo=1',
  odontogram: '/panel/odontograma',
  appointmentHistory: '/panel/historial-citas',
  payments: '/panel/pagos',
  newPayment: '/panel/pagos?nuevo=1',
  reports: '/panel/reportes',
  summary: '/panel/resumen',
  calendar: '/panel/calendario',
  messages: '/panel/mensajes',
  myAppointments: '/panel/mis-citas',
  myPayments: '/panel/mis-pagos',
  myProfile: '/panel/mi-perfil',
  myTreatment: '/panel/mi-tratamiento',
  notFound: '*',
}
