package com.ortos.api.modules.finance;

import com.ortos.api.modules.patients.PacienteRepository;
import com.ortos.api.shared.exception.ApiException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.util.*;

@Service
public class PatientAccountService {
    private final ChargeRepository charges; private final PaymentAllocationRepository allocations; private final PagoRepository payments;
    private final PacienteRepository patients; private final PaymentPlanRepository plans; private final InstallmentRepository installments;
    public PatientAccountService(ChargeRepository charges, PaymentAllocationRepository allocations, PagoRepository payments, PacienteRepository patients, PaymentPlanRepository plans, InstallmentRepository installments) { this.charges=charges; this.allocations=allocations; this.payments=payments; this.patients=patients; this.plans=plans; this.installments=installments; }
    public PatientAccountDto account(String patientId, String appointmentId) {
        if (!patients.existsById(patientId)) throw ApiException.notFound("El paciente no existe.");
        List<Cargo> records = appointmentId == null ? charges.findByPatientIdOrderByCreatedAtDesc(patientId) : charges.findByAppointmentIdOrderByCreatedAtDesc(appointmentId);
        PatientAccountDto result = new PatientAccountDto(); result.setPatientId(patientId); result.setAppointmentId(appointmentId);
        List<ChargeDto> chargeDtos = records.stream().map(this::chargeDto).toList(); result.setCharges(chargeDtos);
        result.setTotalCharged(chargeDtos.stream().filter(c -> !"Anulado".equals(c.getStatus())).map(ChargeDto::getSubtotal).reduce(BigDecimal.ZERO, BigDecimal::add));
        result.setTotalPaid(chargeDtos.stream().map(ChargeDto::getPaid).reduce(BigDecimal.ZERO, BigDecimal::add)); result.setBalance(result.getTotalCharged().subtract(result.getTotalPaid()));
        result.setPayments(payments.findByPatientIdAndStatusNot(patientId, "Anulado").stream().map(this::paymentDto).toList());
        List<PaymentPlanDto> planDtos = plans.findByPatientIdOrderByCreatedAtDesc(patientId).stream().map(this::planDto).toList(); result.setPlans(planDtos);
        result.setNextPayment(planDtos.stream().flatMap(p -> p.getInstallments().stream()).filter(i -> !"Pagada".equals(i.getStatus())).map(InstallmentDto::getDueDate).filter(Objects::nonNull).sorted().findFirst().orElse(null));
        return result;
    }
    @Transactional public ChargeDto createCharge(ChargeDto input) {
        if (input.getPatientId()==null || !patients.existsById(input.getPatientId())) throw ApiException.badRequest("Selecciona un paciente válido.");
        if (input.getDescription()==null || input.getDescription().isBlank() || input.getQuantity()==null || input.getUnitPrice()==null || input.getQuantity().compareTo(BigDecimal.ZERO)<=0 || input.getUnitPrice().compareTo(BigDecimal.ZERO)<0) throw ApiException.badRequest("Descripción, cantidad y precio válidos son obligatorios.");
        Cargo c=new Cargo(); c.setId(UUID.randomUUID().toString()); c.setPatientId(input.getPatientId()); c.setAppointmentId(input.getAppointmentId()); c.setTreatmentId(input.getTreatmentId()); c.setDescription(input.getDescription().trim()); c.setQuantity(input.getQuantity()); c.setUnitPrice(input.getUnitPrice()); c.setSubtotal(input.getQuantity().multiply(input.getUnitPrice()).setScale(2, RoundingMode.HALF_UP)); c.setCreatedAt(LocalDateTime.now()); charges.save(c); return chargeDto(c);
    }
    @Transactional public ChargeDto updateCharge(String id, ChargeDto input) { Cargo c=charges.findById(id).orElseThrow(()->ApiException.notFound("El cargo no existe.")); if (allocations.totalForCharge(id).compareTo(BigDecimal.ZERO)>0) throw ApiException.badRequest("No se puede modificar un cargo con pagos aplicados."); if(input.getQuantity()==null||input.getUnitPrice()==null||input.getQuantity().compareTo(BigDecimal.ZERO)<=0||input.getUnitPrice().compareTo(BigDecimal.ZERO)<0) throw ApiException.badRequest("Cantidad y precio válidos son obligatorios."); c.setDescription(input.getDescription().trim()); c.setQuantity(input.getQuantity());c.setUnitPrice(input.getUnitPrice());c.setSubtotal(input.getQuantity().multiply(input.getUnitPrice()).setScale(2,RoundingMode.HALF_UP));charges.save(c);return chargeDto(c); }
    @Transactional public ChargeDto cancelCharge(String id) { Cargo c=charges.findById(id).orElseThrow(()->ApiException.notFound("El cargo no existe."));if(allocations.totalForCharge(id).compareTo(BigDecimal.ZERO)>0)throw ApiException.badRequest("No se puede anular un cargo con pagos aplicados.");c.setStatus("Anulado");charges.save(c);return chargeDto(c); }
    @Transactional public PaymentPlanDto createPlan(String patientId, PaymentPlanRequest request) { PatientAccountDto account=account(patientId,null); if(request.getInstallmentCount()==null||request.getInstallmentCount()<1||request.getFinancedAmount()==null||request.getFinancedAmount().compareTo(BigDecimal.ZERO)<=0||request.getFinancedAmount().compareTo(account.getBalance())>0)throw ApiException.badRequest("El financiamiento debe corresponder al saldo pendiente y tener cuotas válidas."); PaymentPlan p=new PaymentPlan();p.setId(UUID.randomUUID().toString());p.setPatientId(patientId);p.setTotalAmount(request.getTotalAmount()==null?account.getTotalCharged():request.getTotalAmount());p.setFinancedAmount(request.getFinancedAmount());p.setInstallmentCount(request.getInstallmentCount());p.setCreatedAt(LocalDateTime.now());plans.save(p);LocalDate due=request.getFirstDueDate()==null?LocalDate.now().plusMonths(1):LocalDate.parse(request.getFirstDueDate());BigDecimal base=request.getFinancedAmount().divide(BigDecimal.valueOf(request.getInstallmentCount()),2,RoundingMode.DOWN);BigDecimal remainder=request.getFinancedAmount().subtract(base.multiply(BigDecimal.valueOf(request.getInstallmentCount())));for(int i=1;i<=request.getInstallmentCount();i++){Installment in=new Installment();in.setId(UUID.randomUUID().toString());in.setPaymentPlanId(p.getId());in.setNumber(i);in.setAmount(i==request.getInstallmentCount()?base.add(remainder):base);in.setDueDate(due.plusMonths(i-1));installments.save(in);}return planDto(p); }
    private ChargeDto chargeDto(Cargo c){ChargeDto d=new ChargeDto();d.setId(c.getId());d.setPatientId(c.getPatientId());d.setAppointmentId(c.getAppointmentId());d.setTreatmentId(c.getTreatmentId());d.setDescription(c.getDescription());d.setQuantity(c.getQuantity());d.setUnitPrice(c.getUnitPrice());d.setSubtotal(c.getSubtotal());d.setPaid(allocations.totalForCharge(c.getId()));d.setBalance(c.getSubtotal().subtract(d.getPaid()));d.setStatus("Anulado".equals(c.getStatus())?"Anulado":d.getBalance().signum()==0?"Pagado":d.getPaid().signum()>0?"Parcial":"Pendiente");d.setCreatedAt(c.getCreatedAt().toString());return d;}
    private PaymentDto paymentDto(Pago p){PaymentDto d=new PaymentDto();d.setId(p.getId());d.setPatientId(p.getPatientId());d.setAppointmentId(p.getAppointmentId());d.setAmount(p.getAmount());d.setMethod(p.getMethod());d.setReference(p.getReference());d.setReceiptNumber(p.getReceiptNumber());d.setStatus(p.getStatus());d.setDate(p.getDate().toString());return d;}
    private PaymentPlanDto planDto(PaymentPlan p){PaymentPlanDto d=new PaymentPlanDto();d.setId(p.getId());d.setPatientId(p.getPatientId());d.setTotalAmount(p.getTotalAmount());d.setFinancedAmount(p.getFinancedAmount());d.setInstallmentCount(p.getInstallmentCount());d.setStatus(p.getStatus());List<InstallmentDto> list=installments.findByPaymentPlanIdOrderByNumber(p.getId()).stream().map(i->{InstallmentDto x=new InstallmentDto();x.setId(i.getId());x.setNumber(i.getNumber());x.setAmount(i.getAmount());x.setPaidAmount(i.getPaidAmount());x.setDueDate(i.getDueDate().toString());x.setStatus(i.getPaidAmount().compareTo(i.getAmount())>=0?"Pagada":i.getDueDate().isBefore(LocalDate.now())?"Vencida":"Pendiente");return x;}).toList();d.setInstallments(list);d.setPaidAmount(list.stream().map(InstallmentDto::getPaidAmount).reduce(BigDecimal.ZERO,BigDecimal::add));d.setBalance(p.getFinancedAmount().subtract(d.getPaidAmount()));return d;}
}
