package com.ortos.api.modules.finance;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/** Finance write model for charges generated by a sale. Cargo remains the read model used by legacy account endpoints. */
@Entity
@Table(name = "cargos")
@Getter @Setter
public class SaleCharge {
    @Id private String id;
    @Column(name = "patient_id", nullable = false) private String patientId;
    @Column(name = "sale_id") private String saleId;
    @Column(name = "sale_line_id") private String saleLineId;
    @Column(name = "appointment_id") private String appointmentId;
    @Column(name = "treatment_id") private String treatmentId;
    @Column(nullable = false) private String description;
    @Column(nullable = false, precision = 12, scale = 2) private BigDecimal quantity;
    @Column(name = "unit_price", nullable = false, precision = 12, scale = 2) private BigDecimal unitPrice;
    @Column(nullable = false, precision = 12, scale = 2) private BigDecimal subtotal;
    @Column(nullable = false) private String status = "Pendiente";
    @Column(name = "registered_by") private String registeredBy;
    @Column(name = "created_at", nullable = false) private LocalDateTime createdAt;
}
