export { HomePage } from './HomePage'
export { ServicesPage } from './ServicesPage'
export { SpecialistsPage } from './SpecialistsPage'
export { BookAppointmentPage } from './BookAppointmentPage'
export { DashboardPage } from './DashboardPage'
export { PrivateModulePage } from './PrivateModulePage'
export { NotFoundPage } from './NotFoundPage'
